[package]
name = "rust-scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.18", features = ["train", "wgpu", "autodiff", "ndarray"] }
burn-import = "0.18.0"
csv = "1.3.1"
rand = "0.9.1"
rgb = "0.8.52"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
textplots = "0.8.7"

[[bin]]
name = "train"
path = "src/lib.rs"

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.

[dependencies.godot]
version = "0.2.4"
features = ["experimental-wasm", "lazy-function-tables"]
